const getters = {
  language: state => state.app.language,
  home_search_height: state => state.app.home_search_height,
  home_search_tr_1: state => state.app.home_search_tr_1,
  home_search_tr_2: state => state.app.home_search_tr_2,
  home_search_tr_3: state => state.app.home_search_tr_3,
  home_search_tr_4: state => state.app.home_search_tr_4,
  home_search_tr_5: state => state.app.home_search_tr_5,
  home_search_tr_6: state => state.app.home_search_tr_6,
  crosschain_to_block_detil: state => state.app.crosschain_to_block_detil,
  crosschain_to_block_detil_1: state => state.app.crosschain_to_block_detil_1,
  main_chainblock: state => state.app.main_chainblock,
  main_chain_to_tr: state => state.app.main_chain_to_tr,
  main_chaincommittee: state => state.app.main_chaincommittee,
  fragmented_details: state => state.app.fragmented_details,
  unfragmented_details: state => state.app.unfragmented_details,
  unmain_chainblock: state => state.app.unmain_chainblock,
  main_unchaincommittee: state => state.app.main_unchaincommittee,
  address_details: state => state.app.address_details,
  contract_details: state => state.app.contract_details,
  cross_chain_contract: state => state.app.cross_chain_contract,
  wei_to_de: state => state.app.wei_to_de,
}
export default getters
